export { TelemetryClient, createTelemetryClient } from "./client.js";
export {
  isSensitiveAttributeKey,
  redactText,
  sanitizeAttributes,
  sanitizeResource,
  sanitizeSignal,
  sanitizeUrl,
} from "./sanitize.js";
export type {
  AttributePrimitive,
  Attributes,
  AttributeValue,
  BeforeSend,
  EventSignal,
  ExceptionSignal,
  LogLevel,
  LogSignal,
  MeasurementSignal,
  TelemetryAdapter,
  TelemetryConfig,
  TelemetryErrorContext,
  TelemetryErrorHandler,
  TelemetryResource,
  TelemetrySignal,
  TelemetrySpan,
  TelemetrySpanKind,
  TelemetrySpanOptions,
  TelemetrySpanStatus,
  TraceContext,
} from "./types.js";
